call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP010.json" --folder "CP010 - PING"
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP020.json" --folder "CP020 - TOKEN" --export-environment TEST_CASES.postman_environment.json
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP030.json" --folder "CP030 - TOKEN" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP040.json" --folder "CP040 - CREATE (JSON)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP041.json" --folder "CP041 - CREATE (JSON)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP050.json" --folder "CP050 - CREATE (XML)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP051.json" --folder "CP051 - CREATE (XML)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP060.json" --folder "CP060 - CREATE (URL)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP061.json" --folder "CP061 - CREATE (URL)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP070.json" --folder "CP070 - READ IDs" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP071.json" --folder "CP071 - READ IDs" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP080.json" --folder "CP080 - READ DETAIL" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP090.json" --folder "CP090 - UPDATE (JSON)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP091.json" --folder "CP091 - UPDATE (JSON)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP100.json" --folder "CP100 - UPDATE (XML)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP101.json" --folder "CP101 - UPDATE (XML)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP120.json" --folder "CP120 - UPDATE (URL)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP121.json" --folder "CP121 - UPDATE (URL)" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP130.json" --folder "CP130 - DELETE" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP131.json" --folder "CP131 - DELETE" 
call newman run TEST_CASES.postman_collection.json -e TEST_CASES.postman_environment.json -d "TEST_CASES.DataEntry\CP140.json" --folder "CP140 - CREATE, UPDATE, UPDATE PARTIAL"